name: fhir_bulk
description: A Dart/Flutter package for working with FHIR bulk data. Also includes ability to archive.
version: 0.8.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  archive: ^3.3.0
  fhir: ^0.8.0
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0
  mime: ^1.0.2
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.3
  import_sorter: ^4.6.0
  json_serializable: ^6.2.0
  test: ^1.21.1