name: webauthdemo
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  fhir: ^0.8.0
  fhir_auth:
    path: ../../fhir_auth
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_sign_in: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/