name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.8.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  fhir: ^0.8.0
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0
 

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.3
  import_sorter: ^4.6.0
  json_serializable: ^6.2.0
  test: ^1.21.1


